[[pages]]
path = "streamlit_app.py"
name = "Dashboard Home"
icon = "🏠"

[[pages]]
path = "team1/DashboardFrontPage.py"
name = "Team 1"
icon = "🔖"

[[pages]]
path = "team1/1_Custom Histogram.py"
name = "Team 1 - Histogram"
icon = "📊"

[[pages]]
path = "team1/2_Powerful Data Parser.py"
name = "Team 1 - Data Parser"
icon = "📊"

[[pages]]
path = "team1/3_Data Visualizer.py"
name = "Team 1 - Data Visualizer"
icon = "📊"

[[pages]]
path = "team1/4_Credits & Attributions.py"
name = "Team 1 - Credits"
icon = "📄"

[[pages]]
path = "team3/app.py"
name = "Team 3"
icon = "🔖"

[[pages]]
path = "team4/streamlit_app.py"
name = "Team 4"
icon = "🔖"

[[pages]]
path = "team5/streamlit_app.py"
name = "Team 5"
icon = "🔖"

[[pages]]
path = "teram6/streamlit.py"
name = "Team 6"
icon = "🔖"

[[pages]]
path = "team7/app.py"
name = "Team 7"
icon = "🔖"

[[pages]]
path = "team8/streamlit_app.py"
name = "Team 8"
icon = "🔖"

[[pages]]
path = "team9/streamlit_app.py"
name = "Team 9"
icon = "🔖"

[[pages]]
path = "team10/streamlit_app.py"
name = "Team 10"
icon = "🔖"

[[pages]]
path = "team11/app.py"
name = "Team 11"
icon = "🔖"

[[pages]]
path = "team12/app.py"
name = "Team 12"
icon = "🔖"

[[pages]]
path = "team13/App.py"
name = "Team 13"
icon = "🔖"

[[pages]]
path = "team13/California_Housing_(Streamlit).py"
name = "Team 13 - Visualization 1"
icon = "📊"

[[pages]]
path = "team13/Streamlit_Test.py"
name = "Team 13 - Visualization 2"
icon = "📊"

[[pages]]
path = "team14/app.py"
name = "Team 14"
icon = "🔖"

[[pages]]
path = "team15/app.py"
name = "Team 15"
icon = "🔖"

[[pages]]
path = "team16/alejandro_water_data_analysis.py"
name = "Team 16"
icon = "🔖"

[[pages]]
path = "team17/app.py"
name = "Team 17"
icon = "🔖"

[[pages]]
path = "team18/streamlit_app.py"
name = "Team 18"
icon = "🔖"

[[pages]]
path = "team18/StockCrash.py"
name = "Team 18 - Visualization"
icon = "📊"

[[pages]]
path = "team19/app.py"
name = "Team 19"
icon = "🔖"

[[pages]]
path = "team20/streamlit_app.py"
name = "Team 20"
icon = "🔖"

[[pages]]
path = "team20/1_What_Goes_Into_EJI.py"
name = "Team 20 - Visualization 1"
icon = "📊"

[[pages]]
path = "team20/2_EJI_Scale_and_Categories.py"
name = "Team 20 - Visualization 2"
icon = "📊"

[[pages]]
path = "team20/3_change_over_years_and_comparison.py"
name = "Team 20 - Visualization 3"
icon = "📊"
