# -*- coding: utf-8 -*-
"""Alejandro Water Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJb2dXHfMhG3PDgX5AyVBUSorPF2-Dhh
"""




import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

file_path = "https://raw.githubusercontent.com/kassandrasage24-ctrl/ENG220-19/refs/heads/main/global_water_consumption.csv"
water = pd.read_csv(file_path)
# Assuming 'water' DataFrame is already loaded from previous cells.

st.title("Water Consumption and Scarcity Analysis")

# Graph 1: Rainfall Impact vs. Groundwater Depletion Rate (%)
st.header("Rainfall Impact vs. Groundwater Depletion Rate (%)")
fig1, ax1 = plt.subplots(figsize=(10, 6))
sns.scatterplot(x='Rainfall Impact (Annual Precipitation in mm)', y='Groundwater Depletion Rate (%)', data=water, ax=ax1)
ax1.set_title('Rainfall Impact vs. Groundwater Depletion Rate (%)')
ax1.set_xlabel('Rainfall Impact (Annual Precipitation in mm)')
ax1.set_ylabel('Groundwater Depletion Rate (%)')
ax1.grid(True)
st.pyplot(fig1)

# Graph 2: Total Water Consumption vs. Groundwater Depletion Rate
st.header("Total Water Consumption vs. Groundwater Depletion Rate")
fig2, ax2 = plt.subplots(figsize=(10, 6))
sns.scatterplot(x='Total Water Consumption (Billion Cubic Meters)', y='Groundwater Depletion Rate (%)', data=water, ax=ax2)
ax2.set_title('Total Water Consumption vs. Groundwater Depletion Rate')
ax2.set_xlabel('Total Water Consumption (Billion Cubic Meters)')
ax2.set_ylabel('Groundwater Depletion Rate (%)')
ax2.grid(True)
st.pyplot(fig2)

# Graph 3: Water Scarcity Level Distribution
st.header("Water Scarcity Level Distribution")
fig3, ax3 = plt.subplots(figsize=(8, 8))
counts = water["Water Scarcity Level"].value_counts()
ax3.pie(counts, labels=counts.index, autopct="%1.1f%%", startangle=90)
ax3.set_title("Water Scarcity Level Distribution")
st.pyplot(fig3)
