# -*- coding: utf-8 -*-
"""GlobalWaterConsumption-KatieTran*

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5LTYj94nypWnBsw6Tl7WHnuIkWnF_Lw
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
#accessing the file and dataset from Github
file_path=os.path.join('data', 'global_water_consumption.csv')
df=pd.read_csv(file_path)

df = df[(df['Year'] >= 2000) & (df['Year'] <= 2024)]

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
numeric_cols = [col for col in numeric_cols if col not in ['Year']]

for col in numeric_cols:
    plt.figure(figsize=(12, 7))

    for country, data in df.groupby('Country'):
        plt.plot(data['Year'], data[col], label=country)

    plt.title(f'{col} by Country (2000–2024)', fontsize=14)
    plt.xlabel('Year', fontsize=12)
    plt.ylabel(col, fontsize=12)
    plt.legend(title='Country', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=9)
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.show()