# -*- coding: utf-8 -*-
"""Palko_FinalProj_ENG220.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWROHsJ9Wrnd1NZAaH6Npka4gBb7GLmB
"""

# ENG220 Final Project (Team 18)
# Sasha Palko
# Analyze water consumption by country

# import libraries
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Load dataset
data = pd.read_csv('cleaned_global_water_consumption.csv')

# Add region for each country
first_column = data.columns[0]
unique_values = data[first_column].unique()

unique_df = pd.DataFrame({
    first_column: unique_values,
    'continent': ['South America', 'Oceana', 'South America', 'North America', 'Asia', 'Europe', 'Europe', 'Asia', 'Asia', 'Europe',
                   'Asia', 'North America', 'Asia', 'Europe', 'Africa', 'Asia', 'Europe', 'Europe', 'Europe', 'North America']
})

data = pd.merge(data, unique_df, on=first_column, how='left')

#print(data.head())


#countries_2024 = data.loc[data['Year'] == 2024, 'Country']
#print(countries_2024)
#print(countries_2024.shape[0])

#print(data.groupby("continent")["Per Capita Water Use (Liters per Day)"].mean())
#print(data.columns)

# filter out 2024 data:
use_col = "Per Capita Water Use (Liters per Day)"

data_2024 = data[data["Year"] == 2024]

# Convert the household % into a decimal
data_2024["Household Fraction"] = data_2024["Household Water Use (%)"] / 100

# Multiply to get per capita household usage
data_2024["Per Capita Household Use (L/day)"] = \
        data_2024["Per Capita Water Use (Liters per Day)"] * data_2024["Household Fraction"]
print(data_2024.columns)

########################################################################
################ Avg Per Capita Water Use (L/day) ######################
########################################################################

# Group by continent and get per-capita water use
result = data_2024.groupby("continent")[use_col].mean()
#print(result)



plt.figure(figsize=(8,5))
plt.bar(result.index, result.values)
plt.xlabel("Continent")
plt.ylabel("Avg Per Capita Water Use (L/day)")
plt.title("Average Water Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################ Avg Household Water Use (L/Day) ###########################
########################################################################
use_col = "Per Capita Household Use (L/day)"

# Group by continent and get per-capita water use
result = data_2024.groupby("continent")[use_col].mean()
#print(result)



plt.figure(figsize=(8,5))
plt.bar(result.index, result.values)
plt.xlabel("Continent")
plt.ylabel("Per Capita Household Use (L/day)")
plt.title("Per Capita Household Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################ Avg Agricultural water Use (%) ########################
########################################################################
use_col = "Agricultural Water Use (%)"

# Group by continent and get per-capita water use
result = data_2024.groupby("continent")[use_col].mean()
#print(result)



plt.figure(figsize=(8,5))
plt.bar(result.index, result.values)
plt.xlabel("Continent")
plt.ylabel("% of total water use ")
plt.title("Agricultural Water Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################# Groundwater Depletion Rate (%) #######################
########################################################################
use_col = "Groundwater Depletion Rate (%)"

# Group by continent and get per-capita water use
result = data_2024.groupby("continent")[use_col].mean()
#print(result)



plt.figure(figsize=(8,5))
plt.bar(result.index, result.values)
plt.xlabel("Continent")
plt.ylabel("Groundwater Depletion Rate (%)")
plt.title("Groundwater Depletion Rate by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
############ Rainfall Impact (Annual Precipitation in mm) ##############
########################################################################
use_col = "Rainfall Impact (Annual Precipitation in mm)"

# Group by continent and get per-capita water use
result = data_2024.groupby("continent")[use_col].mean()
#print(result)



plt.figure(figsize=(8,5))
plt.bar(result.index, result.values)
plt.xlabel("Continent")
plt.ylabel("Rainfall Impact (Annual Precipitation in mm)")
plt.title("Rainfall Impact (Annual Precipitation in mm) by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))