# -*- coding: utf-8 -*-
"""Palko_FinalProj_ENG220.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWROHsJ9Wrnd1NZAaH6Npka4gBb7GLmB
"""

# ENG220 Final Project (Team 18)
# Sasha Palko
# Analyze water consumption by country

# import libraries
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Load dataset
data = pd.read_csv('cleaned_global_water_consumption.csv')

# Add region for each country
first_column = data.columns[0]
unique_values = data[first_column].unique()

unique_df = pd.DataFrame({
    first_column: unique_values,
    'continent': ['South America', 'Oceana', 'South America', 'North America', 'Asia', 'Europe', 'Europe', 'Asia', 'Asia', 'Europe',
                   'Asia', 'North America', 'Asia', 'Europe', 'Africa', 'Asia', 'Europe', 'Europe', 'Europe', 'North America']
})

data = pd.merge(data, unique_df, on=first_column, how='left')

#print(data.head())


#countries_2024 = data.loc[data['Year'] == 2024, 'Country']
#print(countries_2024)
#print(countries_2024.shape[0])

#print(data.groupby("continent")["Per Capita Water Use (Liters per Day)"].mean())
print(data.columns)

# filter out 2024 data:
use_col = "Per Capita Water Use (Liters per Day)"

data_2024 = data[data["Year"] == 2024]

# Convert the household % into a decimal
data_2024["Household Fraction"] = data_2024["Household Water Use (%)"] / 100

# Multiply to get per capita household usage
data_2024["Per Capita Household Use (L/day)"] = \
        data_2024["Per Capita Water Use (Liters per Day)"] * data_2024["Household Fraction"]
print(data_2024.columns)

########################################################################
################ Avg Per Capita Water Use (L/day) ######################
########################################################################

# Group by continent and get per-capita water use
result1 = data_2024.groupby("continent")[use_col].mean()
#print(result1)



plt.figure(figsize=(8,5))
plt.bar(result1.index, result1.values)
plt.xlabel("Continent")
plt.ylabel("Avg Per Capita Water Use (L/day)")
plt.title("Average Water Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################ Avg Household Water Use (L/Day) ###########################
########################################################################
use_col = "Per Capita Household Use (L/day)"

# Group by continent and get per-capita water use
result2 = data_2024.groupby("continent")[use_col].mean()
#print(result2)



plt.figure(figsize=(8,5))
plt.bar(result2.index, result2.values)
plt.xlabel("Continent")
plt.ylabel("Per Capita Household Use (L/day)")
plt.title("Per Capita Household Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################ Avg Agricultural water Use (%) ########################
########################################################################
use_col = "Agricultural Water Use (%)"

# Group by continent and get per-capita water use
result3 = data_2024.groupby("continent")[use_col].mean()
#print(result3)



plt.figure(figsize=(8,5))
plt.bar(result3.index, result3.values)
plt.xlabel("Continent")
plt.ylabel("% of total water use ")
plt.title("Agricultural Water Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################# Groundwater Depletion Rate (%) #######################
########################################################################
use_col = "Groundwater Depletion Rate (%)"

# Group by continent and get per-capita water use
result4 = data_2024.groupby("continent")[use_col].mean()
#print4(result)



plt.figure(figsize=(8,5))
plt.bar(result4.index, result4.values)
plt.xlabel("Continent")
plt.ylabel("Groundwater Depletion Rate (%)")
plt.title("Groundwater Depletion Rate by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
############ Rainfall Impact (Annual Precipitation in mm) ##############
########################################################################
use_col = "Rainfall Impact (Annual Precipitation in mm)"

# Group by continent and get per-capita water use
result5 = data_2024.groupby("continent")[use_col].mean()
#print(result5)



plt.figure(figsize=(8,5))
plt.bar(result5.index, result5.values)
plt.xlabel("Continent")
plt.ylabel("Rainfall Impact (Annual Precipitation in mm)")
plt.title("Rainfall Impact (Annual Precipitation in mm) by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

########################################################################
################## Avg Industrial water Use (%) ########################
########################################################################
use_col = "Industrial Water Use (%)"

# Group by continent and get per-capita water use
result6 = data_2024.groupby("continent")[use_col].mean()
#print(result6)



plt.figure(figsize=(8,5))
plt.bar(result6.index, result6.values)
plt.xlabel("Continent")
plt.ylabel("% of total water use ")
plt.title("Industrial Water Use by Continent (2024)")
plt.show()

plt.figure(figsize=(8,5))

#####################################################################################

data_2024['C'] = data_2024['Industrial Water Use (%)'] / data_2024['Per Capita Water Use (Liters per Day)']
print(data_2024.head())

use_col = "C"

# Group by continent and get per-capita water use
result7 = data_2024.groupby("continent")[use_col].mean()
#print(result6)



plt.figure(figsize=(8,5))
plt.bar(result7.index, result7.values)
plt.xlabel("Continent")
plt.ylabel("per capita water usage vs industrial usage")
plt.title("Industrial Water Use by Continent (2024)")
plt.show()

####### AVerage water usage breakdown (World) ############################
average_ind = data_2024['Industrial Water Use (%)'].mean()
average_house = data_2024['Household Water Use (%)'].mean()
average_ag = data_2024['Agricultural Water Use (%)'].mean()

world_values = [average_ind, average_ag, average_house]
world_labels = ["Industrial", "Agricultural", "Household"]

plt.figure(figsize=(6,6))
plt.pie(world_values, labels=world_labels, autopct="%1.1f%%")
plt.title("World Average Water Usage Breakdown (2024)")
plt.show()

############### Average water usage breakdown (Continent) ######################

continent_ind = data_2024.groupby("continent")['Industrial Water Use (%)'].mean()
continent_house = data_2024.groupby("continent")['Household Water Use (%)'].mean()
continent_ag = data_2024.groupby("continent")['Agricultural Water Use (%)'].mean()
print(continent_ind)
print(average_ind)

for continent in continent_ind.index:

    values = [
        continent_ind.loc[continent],
        continent_ag.loc[continent],
        continent_house.loc[continent]
    ]

    labels = ["Industrial", "Agricultural", "Household"]

    plt.figure(figsize=(6,6))
    plt.pie(values, labels=labels, autopct="%1.1f%%")
    plt.title(f"{continent} Water Usage Breakdown (2024)")
    plt.show()



print(data_2024["continent"].value_counts())